### ISSUE TITLE
ipmi plugin : Unable to allocate the FRU: 26

### ISSUE THREAD

**Issue by ymettier** [collectd/collectd#2626]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Ubuntu-14.04

## Expected behavior

Have metrics for temperature as I had with collectd-5.7

## Actual behavior

No metrics for temperature. And I have this in the logs :
```
2017-12-15T09:30:45+00:00 <my hostname> collectd[97564]: ipmi plugin: main(3.2) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-15T09:30:45+00:00 <my hostname> collectd[97564]: ipmi plugin: main(3.1) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-15T09:30:45+00:00 <my hostname> collectd[97564]: ipmi plugin: main(0.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main(5.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.2.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.2.0.0.0 fru.c(fetch_complete): Unable to decode FRU information
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main(10.2) entity.c(fru_fetched_ent_cb):Error fetching entity 10.2 FRU: 26
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.1.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.1.0.0.0 fru.c(fetch_complete): Unable to decode FRU information
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main(10.1) entity.c(fru_fetched_ent_cb):Error fetching entity 10.1 FRU: 26
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.13.0.2.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.13.0.2.0 fru.c(fetch_complete): Unable to decode FRU information
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main(26.2) entity.c(fru_fetched_ent_cb):Error fetching entity 26.2 FRU: 26
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.10.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.10.0.3.0 fru.c(fetch_complete): Unable to decode FRU information
2017-12-15T09:30:46+00:00 <my hostname> collectd[97564]: ipmi plugin: main(11.2) entity.c(fru_fetched_ent_cb):Error fetching entity 11.2 FRU: 26
2017-12-15T09:30:47+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.4.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-15T09:30:47+00:00 <my hostname> collectd[97564]: ipmi plugin: main .1.20.4.0.3.0 fru.c(fetch_complete): Unable to decode FRU information
2017-12-15T09:30:47+00:00 <my hostname> collectd[97564]: ipmi plugin: main(11.1) entity.c(fru_fetched_ent_cb):Error fetching entity 11.1 FRU: 26
```

## Steps to reproduce

* basic installation of Collectd
* ipmi plugin configuration :
```
LoadPlugin ipmi

<Plugin "ipmi">
  <Instance "default">
    Sensor "Exhaust Temp system_board (7.1)"
    Sensor "Inlet Temp system_board (7.1)"
    Sensor "Temp processor (3.1)"
    Sensor "Temp processor (3.2)"
    IgnoreSelected false
    NotifySensorAdd false
    NotifySensorRemove true
    NotifySensorNotPresent false
  </Instance>
</Plugin>
```

Note : if you have any hint to give me, I can investigate myself.

**Comment by rpv-tomsk** [comment]
Hi!

Which version of OpenIPMI you have installed?

**Comment by ymettier** [comment]
Hello,

I'm not sure how I can get openipmi version. Maybe that way ?

```
% dpkg -l|grep openipmi
ii  libopenipmi0                         2.0.18-0ubuntu7.2                   amd64        Intelligent Platform Management Interface - runtime
ii  openipmi                             2.0.18-0ubuntu7.2                   amd64        Intelligent Platform Management Interface (for servers)
```

And yes, I used collectd-5.7 with the same version.
Step I did :
1/ Install openipmi and collectd-5.7 (a long time ago)
2/ no problem with ipmi
3/ upgrade collectd to 5.8 (and upgrade only collectd)
4/ notice that I have no more metrics about ipmi; and messages in the log.

**Comment by rpv-tomsk** [comment]
Can you try to use recent OpenIPMI version?
2.0.18 has many bugs which are fixed in recent versions.

**Comment by ymettier** [comment]
Same problem with openipmi-2.0.24.

Here are the logs :
```
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main(3.2) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main(3.1) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main(11.4) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main(0.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main .1.20.2.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main .1.20.1.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main .1.20.12.0.1.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:39:32+00:00 <my hostname> collectd[34895]: ipmi plugin: main .1.20.10.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:39:33+00:00 <my hostname> collectd[34895]: ipmi plugin: main .1.20.4.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
```

**Comment by ymettier** [comment]
Some good news (but not fully fixed for me)

With openipmi-2.0.24 and with this configuration file, I have the metrics I want :
```
LoadPlugin ipmi

<Plugin "ipmi">
#    Sensor "Exhaust Temp system_board (7.1)"
#    Sensor "Inlet Temp system_board (7.1)"
#    Sensor "Temp processor (3.1)"
#    Sensor "Temp processor (3.2)"
    IgnoreSelected false
    NotifySensorAdd false
    NotifySensorRemove true
    NotifySensorNotPresent false
</Plugin>
```

Here is what I get :
```
# collectdctl listval|grep ipmi
<my hostname>/ipmi/current-Current 2 power_supply (10.2)
<my hostname>/ipmi/current-Pwr Consumption system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan1A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan1B system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan2A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan2B system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan3A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan3B system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan4A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan4B system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan5A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan5B system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan6A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan6B system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan7A system_board (7.1)
<my hostname>/ipmi/fanspeed-Fan7B system_board (7.1)
<my hostname>/ipmi/temperature-Exhaust Temp system_board (7.1)
<my hostname>/ipmi/temperature-Inlet Temp system_board (7.1)
<my hostname>/ipmi/temperature-Temp processor (3.1)
<my hostname>/ipmi/temperature-Temp processor (3.2)
<my hostname>/ipmi/voltage-Voltage 2 power_supply (10.2)
```

My question now becomes : how to specify the 4 temperature sensors I want and only them ?
And why does my old configuration file not working ?

Additionnal information with this configuration file... Here is the log :
```
2017-12-19T09:59:09+00:00 <my hostname> collectd[44231]: ipmi plugin: Legacy configuration found! Please update your config file.
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: sensor_list_add: Ignore sensor `B 12 memory_device (32.1)` of `main`, because it is discrete (0xc)! Its type: (0x6f, memory). 

[... lots of "ipmi plugin: sensor_list_add: Ignore sensor ... because it is discrete" ...]

2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: sensor_list_add: Ignore sensor `SEL system_board (7.1)` of `main`, because it is discrete (0x10)! Its type: (0x6f, event_logging_disabled). 
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main(3.2) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main(3.1) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main(11.4) entity.c(ipmi_entity_fetch_frus_cb): Unable to allocate the FRU: 26
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main(0.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main .1.20.2.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main .1.20.1.0.0.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main .1.20.12.0.1.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main .1.20.10.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
2017-12-19T09:59:13+00:00 <my hostname> collectd[44231]: ipmi plugin: main .1.20.4.0.3.0 normal_fru.c(process_fru_info): FRU fields did not occur in the correct order
```
(No problem with the ignored sensors : i noticed that is a new feature of 5.8.0)

**Comment by ymettier** [comment]
I'm checking on another server with openipmi-2.0.18 (ubuntu) : I get the metrics with this configuration file :

```
LoadPlugin ipmi

<Plugin "ipmi">
#  Sensor "Exhaust Temp system_board (7.1)"
#  Sensor "Inlet Temp system_board (7.1)"
#  Sensor "Temp processor (3.1)"
#  Sensor "Temp processor (3.2)"
  IgnoreSelected false
  NotifySensorAdd false
  NotifySensorRemove true
  NotifySensorNotPresent false
</Plugin>
```

So the version of openipmi has nothing to do with my problem.

Now I'm searching how to get my 4 metrics and not all the others (that worked with collectd-5.7.2)

**Comment by rpv-tomsk** [comment]
>Same problem with openipmi-2.0.24.
>Here are the logs :

The collectd-5.8, unlike to collectd-5.7, sets log handler to openipmi. 
So, you just see some messages which you could not see in collectd-5.7.

Collectd does not use FRU, so all messages related to FRU are not useful.
The only useful one is the message related to SDR:

>2017-12-19T09:59:11+00:00 <my hostname> collectd[44231]: ipmi plugin: main(0.20)(s,0) sdr.c(handle_sdr_data): SDR fetch error getting sdr 0x0: c1

0xC1 means something like 'invalid command'. Than can occur if sensor is disabled/not present.
There is some flags exists, we try to handle them, but they are not always correct / succesfull.

**Comment by rpv-tomsk** [comment]
Can you please show `ipmitool sensor` and highlight sensors you are missing in Collectd?

**Comment by ymettier** [comment]
```
# ipmitool sensor |grep -i temp
Inlet Temp       | 25.000     | degrees C  | ok    | na        | -7.000    | 3.000     | 42.000    | 47.000    | na        
Exhaust Temp     | 41.000     | degrees C  | ok    | na        | 0.000     | 0.000     | 70.000    | 75.000    | na        
Temp             | 55.000     | degrees C  | ok    | na        | 3.000     | 8.000     | 88.000    | 93.000    | na        
Temp             | 58.000     | degrees C  | ok    | na        | 3.000     | 8.000     | 88.000    | 93.000    | na        
Mem Overtemp     | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
```
I would like the 4 sensors that have a value in degree C.

**Comment by rpv-tomsk** [comment]
Unfortunately, collectd-5.8 has a bug caused by typo.
Fix:
```
--- a/src/ipmi.c
+++ b/src/ipmi.c
@@ -1065,7 +1065,7 @@ static int c_ipmi_config_add_instance(oconfig_item_t *ci) {
     oconfig_item_t *child = ci->children + i;

     if (strcasecmp("Sensor", child->key) == 0)
-      ignorelist_add(st->ignorelist, ci->values[0].value.string);
+      ignorelist_add(st->ignorelist, child->values[0].value.string);
     else if (strcasecmp("IgnoreSelected", child->key) == 0) {
       _Bool t;
       status = cf_util_get_boolean(child, &t);
```

**Comment by ymettier** [comment]
Thanks for the patch. It works for me !

You can close this issue.
