### ISSUE TITLE
Can't stop collectd when write_graphite is enabled and it can not connect with graphite server

### ISSUE THREAD

**Issue by patrickshan** [collectd/collectd#315]
When I enabled write_graphite module and collectd can not connect with the graphite server (because of the firewall of the graphite server didn't set up properly for that collectd client server), the init script can not stop the collectd process (this is done by start-stop-daemon on ubuntu). You need to use kill -9 to kill all the collectd processes.
I am not sure if it is because collectdmon doesn't process the signal properly when write_graphite plugin connects time out.

**Comment by octo** [comment]
Is it possible that this has been fixed by #1104?

**Comment by magnetik** [comment]
This bug is quite old but i'm still facing it using collectd 5.7 (`collectd 5.7.2.sfx0`)

**Comment by NikolaeVarius** [comment]
I'm facing this issue with the Kafka Plugin. I can see the TCP connection to Kafka stuck on  CLOSE_WAIT.

Init script can't restart it so I need to hard kill.

`sudo service collectd restart
 * Restarting statistics collection and monitoring daemon collectd                                                                                                                . . . . . . . . . . . . . . . .                                                                                                                                          [fail]`

This is on collectd 5.7/
