### ISSUE TITLE
COLLECTD_INTERVAL and COLLECTD_HOSTNAME are not being exported

### ISSUE THREAD

**Issue by rssh22** [collectd/collectd#3942]
*   Version of collectd: 5.10.0,REV=2019.11.15
*   Operating system / distribution: Solaris 10
*   Kernel version (if applicable): Oracle Solaris 10 1/13 s10s_u11wos_24a SPARC

## Expected behavior
COLLECTD_INTERVAL and COLLECTD_HOSTNAME should be exported before calling COLLECTD EXEC PLUGIN scripts

## Actual behavior
COLLECTD_INTERVAL and COLLECTD_HOSTNAME are not being exported

these are the only environment variables received by the exec script

DEBUG:root:varenv: LC_NUMERIC = C
DEBUG:root:varenv: TZ = Europe/Madrid
DEBUG:root:varenv: SMF_METHOD = /var/opt/csw/svc/method/svc-cswcollectd start
DEBUG:root:varenv: SMF_FMRI = svc:/network/cswcollectd:default
DEBUG:root:varenv: SMF_RESTARTER = svc:/system/svc/restarter:default
DEBUG:root:varenv: PATH = /opt/csw/sbin:/usr/sbin:/usr/bin

## Steps to reproduce

*   Normal use of the recommended way of usage of the exec plugin:
```
#!/usr/bin/python
import logging, os

script_filename = os.path.basename(__file__)
logdir = "/diagnostics/wld-pre-10/wls-pre-10-c1-m1-n2/logs/"
log_filename = logdir + script_filename + ".log"
level=logging.DEBUG

logging.basicConfig(filename=log_filename, encoding='utf-8', level=level)
for varenv in os.environ:
 logging.debug("varenv: " + varenv + " = " + os.environ[varenv])
```

**Comment by dago** [comment]
Hi,

is this fixed in 5.12.0 which you request for the specific platform here?
  https://www.opencsw.org/mantis/view.php?id=5340

Best regards -- Dago

**Comment by rssh22** [comment]
Hi @dago ,

I'm testing 5.12.0 in deep. However, It seems that the problem persists:

```
2021-11-25 12:59:32,231 - DEBUG - varenv: USERNAME = bea
2021-11-25 12:59:32,233 - DEBUG - varenv: SUDO_COMMAND = /bin/bash -c /etc/opt/csw/collectd.exec.scripts/collectd_check_wls_pcpu.py -w wls-pre-10-c1-m1-n2 -d wld-pre-10
2021-11-25 12:59:32,233 - DEBUG - varenv: TERM = xterm
2021-11-25 12:59:32,234 - DEBUG - varenv: SHELL = /bin/bash
2021-11-25 12:59:32,234 - DEBUG - varenv: TZ = Europe/Madrid
2021-11-25 12:59:32,234 - DEBUG - varenv: SHLVL = 1
2021-11-25 12:59:32,234 - DEBUG - varenv: SUDO_UID = 0
2021-11-25 12:59:32,234 - DEBUG - varenv: SUDO_GID = 0
2021-11-25 12:59:32,234 - DEBUG - varenv: PWD = /export/home/bea
2021-11-25 12:59:32,234 - DEBUG - varenv: LOGNAME = bea
2021-11-25 12:59:32,235 - DEBUG - varenv: USER = bea
2021-11-25 12:59:32,235 - DEBUG - varenv: PATH = /usr/sbin:/usr/bin:/usr/ccs/bin:/usr/openwin/bin:/usr/dt/bin:/opt/SUNWjass/bin:/usr/platform/sun4v/sbin:/usr/local/bin
2021-11-25 12:59:32,235 - DEBUG - varenv: MAIL = /var/mail/bea
2021-11-25 12:59:32,235 - DEBUG - varenv: SUDO_USER = root
2021-11-25 12:59:32,235 - DEBUG - varenv: PS1 = \[\e]0;\u@\h [$R] \w\a\]\n\[\e[32m\]\t \u@\h \[\e[33m\]\w\[\e[0m\]\n\$
2021-11-25 12:59:32,235 - DEBUG - varenv: HOME = /export/home/bea
2021-11-25 12:59:32,235 - DEBUG - varenv: DISPLAY = localhost:14.0
2021-11-25 12:59:32,236 - DEBUG - varenv: _ = /etc/opt/csw/collectd.exec.scripts/collectd_check_wls_pcpu.py
2021-11-25 12:59:32,236 - DEBUG - varenv: EDITOR = vi
```

```
# pkginfo -l CSWcollectd
   PKGINST:  CSWcollectd
      NAME:  collectd - Collects system performance statistics periodically
  CATEGORY:  application
      ARCH:  sparc
   VERSION:  5.12.0,REV=2021.11.22
   BASEDIR:  /
    VENDOR:  http://collectd.org/ packaged for CSW by Dagobert Michelsen
    PSTAMP:  dam@unstable10s-20211122152334
  INSTDATE:  Nov 25 2021 12:30
   HOTLINE:  http://www.opencsw.org/bugtrack/
     EMAIL:  dam@opencsw.org
    STATUS:  completely installed
     FILES:      220 installed pathnames
                  10 shared pathnames
                  26 directories
                 168 executables
                9407 blocks used (approx)


```

**Comment by rssh22** [comment]
Sorry for my previous comment. It seems that it is getting properly the env variable COLLECTD_INTERVAL:
```
2021-11-25 15:16:26,882 - DEBUG - varenv: LC_NUMERIC = C
2021-11-25 15:16:26,883 - DEBUG - varenv: TZ = Europe/Madrid
2021-11-25 15:16:26,883 - DEBUG - varenv: SMF_METHOD = /var/opt/csw/svc/method/svc-cswcollectd start
2021-11-25 15:16:26,883 - DEBUG - varenv: SMF_FMRI = svc:/network/cswcollectd:default
2021-11-25 15:16:26,884 - DEBUG - varenv: COLLECTD_HOSTNAME = mekosb2
2021-11-25 15:16:26,884 - DEBUG - varenv: SMF_RESTARTER = svc:/system/svc/restarter:default
2021-11-25 15:16:26,884 - DEBUG - varenv: COLLECTD_INTERVAL = 30.000
2021-11-25 15:16:26,884 - DEBUG - varenv: PATH = /opt/csw/sbin:/usr/sbin:/usr/bin
```

**Comment by VitalyArtemiev** [comment]
Same issue on CentOS Stream 8 intermittently.

**Comment by eero-t** [comment]
> Same issue on CentOS Stream 8 intermittently.

Which version of collectd that has?  And what _exactly_ "intermittently" means?

(@rssh22's comment from few years ago indicates that this bug should have been fixed in collectd v5.12.)
